// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:google_sign_in/google_sign_in.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbRybis6zyI6-k5XkzDP7LPFzkp-m-lbI',
    appId: '1:544226191997:web:b307ebcb15e96405d0df14',
    messagingSenderId: '544226191997',
    projectId: 'kopma-uin-suka-c3370',
    authDomain: 'kopma-uin-suka-c3370.firebaseapp.com',
    storageBucket: 'kopma-uin-suka-c3370.appspot.com',
    measurementId: 'G-S3Q0D55G58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8pZ5yLFPIHZmhZFmDStc6BQ6ZMyQKqno',
    appId: '1:544226191997:android:bfa6c753c5f42b00d0df14',
    messagingSenderId: '544226191997',
    projectId: 'kopma-uin-suka-c3370',
    storageBucket: 'kopma-uin-suka-c3370.appspot.com',
  );
}

const iOSClientId = 'your-client-id.apps.googleusercontent.com';
const webClientId = 'your-client-id.apps.googleusercontent.com';


String get googleClientId {
  return switch (defaultTargetPlatform) {
    TargetPlatform.iOS || TargetPlatform.macOS => iOSClientId,
    _ => webClientId,
  };
}

